#!/usr/bin/env node
// Keeps the README's coverage and size badges honest.
//
// shields.io can render npm version and licence live, but it has no live
// source for either of the numbers we care about: its bundlephobia badges
// answer "rate limited by upstream service" (which is what would appear in
// the README), and npm/unpacked-size reports the whole tarball — sourcemaps,
// both module formats and the .d.ts tree — which is not what anyone ships.
//
// So we measure our own dist and write static badges, and CI re-measures and
// fails if the README has drifted. A static badge that cannot go stale is
// worth more than a live badge that renders an error string.
//
//   node scripts/badges.mjs --write   update the README
//   node scripts/badges.mjs --check   fail if the README disagrees (CI)
//
// Requires `pnpm build` and `pnpm test:coverage` to have run first.

import { gzipSync } from "node:zlib";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const readmePath = resolve(pkgRoot, "../../README.md");
// The gallery states the same two numbers in its sidebar. It reads them from
// here rather than repeating the literals, so there is one measurement and
// one place for it to be wrong.
const measuredPath = resolve(pkgRoot, "../../apps/docs/src/measured.json");

const START = "<!-- badges:start -->";
const END = "<!-- badges:end -->";

// Drift under these is noise — a comment added to a component moves the gzip
// size by a few bytes and nobody wants a red build for it.
const TOLERANCE = { coveragePoints: 1, sizeKb: 1 };

const die = (msg) => {
  console.error(`badges: ${msg}`);
  process.exit(1);
};

/** Gzipped kB of what a consumer actually downloads: the ESM bundle plus the
 *  stylesheet. tokens.css is excluded — its contents are already inside
 *  space-ui.css, and the separate entry exists only for reading the defaults. */
const measureSize = () => {
  const parts = ["dist/index.js", "dist/space-ui.css"].map((f) => {
    const p = resolve(pkgRoot, f);
    if (!existsSync(p)) die(`${f} is missing — run \`pnpm build\` first`);
    return gzipSync(readFileSync(p), { level: 9 }).length;
  });
  return parts.reduce((a, b) => a + b, 0) / 1024;
};

const measureCoverage = () => {
  const p = resolve(pkgRoot, "coverage/coverage-summary.json");
  if (!existsSync(p)) die("coverage-summary.json is missing — run `pnpm test:coverage` first");
  const pct = JSON.parse(readFileSync(p, "utf8")).total?.statements?.pct;
  if (typeof pct !== "number") die("coverage-summary.json has no total.statements.pct");
  return pct;
};

// shields' own thresholds, so the colour means the same here as everywhere.
const coverageColor = (pct) =>
  pct >= 90 ? "brightgreen" : pct >= 80 ? "green" : pct >= 70 ? "yellowgreen" : pct >= 60 ? "yellow" : "orange";

const badge = (label, message, color) =>
  `https://img.shields.io/badge/${encodeURIComponent(label)}-${encodeURIComponent(message)}-${color}`;

const render = ({ coverage, sizeKb }) => {
  const pkg = "@inkorange/space-ui";
  const docs = "https://space-components.vercel.app";
  return [
    START,
    "",
    `[![npm](https://img.shields.io/npm/v/${pkg})](https://www.npmjs.com/package/${pkg})`,
    `![coverage](${badge("coverage", `${coverage.toFixed(0)}%`, coverageColor(coverage))})`,
    `![minzip](${badge("minzip", `${sizeKb.toFixed(1)} kB`, "blue")})`,
    `![dependencies](${badge("dependencies", "0", "blue")})`,
    `[![docs](${badge("docs", "live gallery", "0b7dd6")})](${docs})`,
    "",
    END,
  ].join("\n");
};

const parseExisting = (readme) => {
  const block = readme.slice(readme.indexOf(START), readme.indexOf(END) + END.length);
  const num = (re) => {
    const m = block.match(re);
    return m ? Number(m[1]) : null;
  };
  return {
    coverage: num(/badge\/coverage-(\d+(?:\.\d+)?)%25/),
    sizeKb: num(/badge\/minzip-(\d+(?:\.\d+)?)%20kB/),
  };
};

const mode = process.argv[2];
if (mode !== "--write" && mode !== "--check") die("pass --write or --check");

const measured = { coverage: measureCoverage(), sizeKb: measureSize() };
const readme = readFileSync(readmePath, "utf8");
const hasBlock = readme.includes(START) && readme.includes(END);

if (mode === "--write") {
  if (!hasBlock) die(`README.md has no ${START} … ${END} block`);
  const next =
    readme.slice(0, readme.indexOf(START)) +
    render(measured) +
    readme.slice(readme.indexOf(END) + END.length);
  writeFileSync(readmePath, next);
  writeFileSync(
    measuredPath,
    JSON.stringify(
      {
        _comment:
          "Generated by packages/space-ui/scripts/badges.mjs. Do not edit — run `pnpm --filter @inkorange/space-ui badges:write`.",
        coverageStatementsPct: Number(measured.coverage.toFixed(2)),
        minzipKb: Number(measured.sizeKb.toFixed(1)),
      },
      null,
      2,
    ) + "\n",
  );
  console.log(
    `badges: coverage ${measured.coverage.toFixed(2)}% · minzip ${measured.sizeKb.toFixed(1)} kB — README updated`,
  );
  process.exit(0);
}

if (!hasBlock) die(`README.md has no ${START} … ${END} block`);
const claimed = parseExisting(readme);
const problems = [];
if (claimed.coverage === null) problems.push("no coverage badge found in the block");
else if (Math.abs(claimed.coverage - measured.coverage) > TOLERANCE.coveragePoints)
  problems.push(
    `coverage badge says ${claimed.coverage}%, measured ${measured.coverage.toFixed(2)}%`,
  );
if (claimed.sizeKb === null) problems.push("no minzip badge found in the block");
else if (Math.abs(claimed.sizeKb - measured.sizeKb) > TOLERANCE.sizeKb)
  problems.push(`minzip badge says ${claimed.sizeKb} kB, measured ${measured.sizeKb.toFixed(1)} kB`);

// The gallery quotes the same numbers, so it drifts the same way.
if (!existsSync(measuredPath)) problems.push("apps/docs/src/measured.json is missing");
else {
  const doc = JSON.parse(readFileSync(measuredPath, "utf8"));
  if (Math.abs((doc.coverageStatementsPct ?? -1) - measured.coverage) > TOLERANCE.coveragePoints)
    problems.push(
      `measured.json coverage says ${doc.coverageStatementsPct}%, measured ${measured.coverage.toFixed(2)}%`,
    );
  if (Math.abs((doc.minzipKb ?? -1) - measured.sizeKb) > TOLERANCE.sizeKb)
    problems.push(`measured.json minzip says ${doc.minzipKb} kB, measured ${measured.sizeKb.toFixed(1)} kB`);
}

if (problems.length) {
  console.error("badges: README is out of date —");
  for (const p of problems) console.error(`  · ${p}`);
  console.error("\nRun `pnpm --filter @inkorange/space-ui badges:write` and commit the result.");
  process.exit(1);
}
console.log(
  `badges: README matches — coverage ${measured.coverage.toFixed(2)}%, minzip ${measured.sizeKb.toFixed(1)} kB`,
);
